package:
  name: xonsh
  version: {{ GIT_DESCRIBE_TAG + '.dev' + GIT_DESCRIBE_NUMBER }}

source:
   git_url: ../

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 0
  string: {{'py' + CONDA_PY + '_' + GIT_DESCRIBE_HASH }}
  skip: True  # [py2k]
  entry_points:
    - xonsh = xonsh.main:main

requirements:
  build:
    - python
    - ply
    - setuptools
    - jupyter
  run:
    - python
    - ply
    - prompt_toolkit
    - setproctitle
    - pygments

app:
  entry: xonsh
  icon: ../docs/_static/ascii_conch_part_color.png

about:
  home: http://xon.sh/
  license: BSD
  summary: xonsh is a Python-ish, BASHwards-facing shell.

